[package]
name = "rfraylib" # "raylib2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1"
raylib4-sys = { git = "ssh://git@github.com/sile/raylib4-sys" }
thiserror = "1"

[dev-dependencies]
anyhow = "1"
